### ISSUE TITLE
Reading Data from widgetTask () every 1 minute

### ISSUE THREAD

**Issue by creativemind1** [lucas-kejan/react-native-widget#1]
Hello,

The widget displaying data with the below code when we first run for the first time. And when we close the App, the widget will remain same. Now how do I run the below function in the widgetTask.js even though the app is not in ON mode and even though the screen is OFF mode?

```
export default async function widgetTask (taskData: TaskInfo) {

}
```

**Comment by creativemind1** [comment]
I solved this man.. 

`'react-native-background-timer'` did the job

```
export default async function widgetTask (taskData: TaskInfo) {
const EventEmitter = Platform.select({
    ios: () => NativeAppEventEmitter,
    android: () => DeviceEventEmitter,
  })();
  // start a global timer
  bgTimer.start(10000); // delay in milliseconds only for Android
  // listen for event
  EventEmitter.addListener('backgroundTimer', () => {
    // this will be executed once after 10 seconds
    getValue() <!-- Call after 
  });
}
```

**Comment by jafarpishdadi** [comment]
hi @creativemind1 
thanks 
this replay not work for widget when app closed
